Update `selenium-webdriver`
To resolve the very distracting error in the test output:

```
<NoMethodError: undefined method 'logs' for an instance of Selenium::WebDriver::Chrome::Driver>
```

`webdrivers` gem is removed because it's no longer necessary for the
newly updated version of `selenium-webdriver`.